main:
  classes: [0, 1, 2]
  epochs: 100
  batch_size: 32
  model: "resnet50"
  optim: "Adam"
  load: False
  shape: [256, 256]
  patience: 5
  stop_cond: "mIoU"
  cv: 3
  result_dir: "/mnt/ssdwdc/chemotherapy_strage/result/"
  
dataset:
  imgs_dir: "/mnt/ssdwdc/chemotherapy_strage/mnt2/"

test:
  model_path:  ""
  output_dir: "/mnt/ssdwdc/chemotherapy_strage/result/test/"
  jb_dir: "/mnt/ssdwdc/chemotherapy_strage/dataset/"
  target_data: "test"
  get_miss: False
  likelihood: True
  cv_num: 0
