main:
  classes: [0, 1, 2]
  epochs: 100
  batch_size: 128
  model: "resnet50"
  optim: "Adam"
  load: False
  shape: [256, 256]
  level: 1
  patience: 5
  stop_cond: "mIoU"
  cv: 3
  jb_dir: "/mnt/ssdwdc/chemotherapy_strage/dataset/10_valwsi_LEV1/"
  result_dir: "/mnt/ssdwdc/chemotherapy_strage/result_10_valwsi_LEV1/"
  
dataset:
  imgs_dir: "/mnt/ssdwdc/chemotherapy_strage/mnt2_LEV1/"

test:
  weight_dir: "/mnt/ssdwdc/chemotherapy_strage/result_10_valwsi_LEV1/checkpoints/[0, 1, 2]/"
  weight_names:
    - "cv0_epoch7_best_val_mIoU.pth"
    - "cv1_epoch3_best_val_mIoU.pth"
    - "cv2_epoch5_best_val_mIoU.pth"
  output_dir: "/mnt/ssdwdc/chemotherapy_strage/result_10_valwsi_LEV1/test/"
  target_data: "test"
  get_miss: False
  likelihood: False
