main:
  classes: [0, 1, 2]
  epochs: 100
  batch_size: 32
  model: "resnet50"
  optim: "Adam"
  load: False
  shape: [256, 256]
  patience: 5
  stop_cond: "mIoU"
  cv: 3
  jb_dir: "/mnt/ssdwdc/chemotherapy_strage/dataset/"
  result_dir: "/mnt/ssdwdc/chemotherapy_strage/result/"
  
dataset:
  imgs_dir: "/mnt/ssdwdc/chemotherapy_strage/mnt2_LEV0/"

test:
  weight_dir: "/mnt/ssdwdc/chemotherapy_strage/result/checkpoints/[0, 1, 2]/"
  weight_names:
    - "cv0_epoch9_best_val_mIoU.pth"
    - "cv1_epoch16_best_val_mIoU.pth"
    - "cv2_epoch13_best_val_mIoU.pth"
  output_dir: "/mnt/ssdwdc/chemotherapy_strage/result/test/"
  target_data: "test"
  get_miss: False
  likelihood: True
